server:
  port: 9000

eureka:
  instance:
    hostname: spring-cloud-manager
    status-page-url: http://${spring.cloud.client.ip-address}:${server.port}/swagger-ui.html#/
#  client:
#    service-url:
#      defaultZone:   http://localhost:10000/eureka/

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_cloud?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root

mybatis:
  type-aliases-package: com.hzy.springcloud.manager.model
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: true
  support-methods-arguments: true

logging:
  config: classpath:logback-spring.xml


